[theme]
# A dark-blue primary accent color for interactive elements
primaryColor = "#0da13c"

# A light "white-blue" background color for the main content area
backgroundColor = "#FFE8D6"

# A lighter background color for the sidebar and other components
secondaryBackgroundColor = "#ffffff"

# A darker text color for better contrast against the light background
textColor = "#000000"
